version: "3.5"

services:
  db:
    restart: always
    image: postgres:12.1
    container_name: db
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend: &backend
    restart: always
    image: geoloc_backend:latest
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: start-backend
    stdin_open: true
    tty: true

volumes:
  db-data:
