# Generated by Django 3.2.5 on 2021-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('continent_code', models.CharField(max_length=5)),
                ('continent_name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=20)),
                ('region_code', models.CharField(max_length=5)),
                ('region_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
            ],
        ),
    ]
